api_url: http://localhost:8080/
harvest_delay: .5
logging_level: INFO
whitelist:
  - name: user
    uuid: uuid
    phone_number: "+..."
    kernel_name: "run `jupyter kernelspec list` to get the full list of kernels that can be started"
    kernel_connection_file: "run `jupyter --runtime-dir` to see all connection files, i.e. of probably running kernels"
  